//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DanicoModel", "FK_Hotel_Town", "Town", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DanicoProject.Models.Town), "Hotel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DanicoProject.Models.Hotel), true)]
[assembly: EdmRelationshipAttribute("DanicoModel", "FK_HotelService_Hotel", "Hotel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DanicoProject.Models.Hotel), "HotelService", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DanicoProject.Models.HotelService), true)]
[assembly: EdmRelationshipAttribute("DanicoModel", "FK_TripType_Hotel", "Hotel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DanicoProject.Models.Hotel), "TripType", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DanicoProject.Models.TripType), true)]
[assembly: EdmRelationshipAttribute("DanicoModel", "FK_HotelService_Room", "Room", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DanicoProject.Models.Room), "HotelService", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DanicoProject.Models.HotelService), true)]
[assembly: EdmRelationshipAttribute("DanicoModel", "FK_HotelService_Service", "Service", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DanicoProject.Models.Service), "HotelService", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DanicoProject.Models.HotelService), true)]

#endregion

namespace DanicoProject.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AllConection : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AllConection object using the connection string found in the 'AllConection' section of the application configuration file.
        /// </summary>
        public AllConection() : base("name=AllConection", "AllConection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AllConection object.
        /// </summary>
        public AllConection(string connectionString) : base(connectionString, "AllConection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AllConection object.
        /// </summary>
        public AllConection(EntityConnection connection) : base(connection, "AllConection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hotel> Hotels
        {
            get
            {
                if ((_Hotels == null))
                {
                    _Hotels = base.CreateObjectSet<Hotel>("Hotels");
                }
                return _Hotels;
            }
        }
        private ObjectSet<Hotel> _Hotels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HotelService> HotelServices
        {
            get
            {
                if ((_HotelServices == null))
                {
                    _HotelServices = base.CreateObjectSet<HotelService>("HotelServices");
                }
                return _HotelServices;
            }
        }
        private ObjectSet<HotelService> _HotelServices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Room> Rooms
        {
            get
            {
                if ((_Rooms == null))
                {
                    _Rooms = base.CreateObjectSet<Room>("Rooms");
                }
                return _Rooms;
            }
        }
        private ObjectSet<Room> _Rooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Service> Services
        {
            get
            {
                if ((_Services == null))
                {
                    _Services = base.CreateObjectSet<Service>("Services");
                }
                return _Services;
            }
        }
        private ObjectSet<Service> _Services;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Town> Towns
        {
            get
            {
                if ((_Towns == null))
                {
                    _Towns = base.CreateObjectSet<Town>("Towns");
                }
                return _Towns;
            }
        }
        private ObjectSet<Town> _Towns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TripType> TripTypes
        {
            get
            {
                if ((_TripTypes == null))
                {
                    _TripTypes = base.CreateObjectSet<TripType>("TripTypes");
                }
                return _TripTypes;
            }
        }
        private ObjectSet<TripType> _TripTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vHotel> vHotels
        {
            get
            {
                if ((_vHotels == null))
                {
                    _vHotels = base.CreateObjectSet<vHotel>("vHotels");
                }
                return _vHotels;
            }
        }
        private ObjectSet<vHotel> _vHotels;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hotels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHotels(Hotel hotel)
        {
            base.AddObject("Hotels", hotel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HotelServices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHotelServices(HotelService hotelService)
        {
            base.AddObject("HotelServices", hotelService);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRooms(Room room)
        {
            base.AddObject("Rooms", room);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Services EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServices(Service service)
        {
            base.AddObject("Services", service);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Towns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTowns(Town town)
        {
            base.AddObject("Towns", town);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TripTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTripTypes(TripType tripType)
        {
            base.AddObject("TripTypes", tripType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vHotels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovHotels(vHotel vHotel)
        {
            base.AddObject("vHotels", vHotel);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="Hotel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hotel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hotel object.
        /// </summary>
        /// <param name="pk_idHotel">Initial value of the pk_idHotel property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="fk_idTown">Initial value of the fk_idTown property.</param>
        /// <param name="state">Initial value of the state property.</param>
        public static Hotel CreateHotel(global::System.Int64 pk_idHotel, global::System.String name, global::System.String address, global::System.String description, global::System.Int64 fk_idTown, global::System.Boolean state)
        {
            Hotel hotel = new Hotel();
            hotel.pk_idHotel = pk_idHotel;
            hotel.name = name;
            hotel.address = address;
            hotel.description = description;
            hotel.fk_idTown = fk_idTown;
            hotel.state = state;
            return hotel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pk_idHotel
        {
            get
            {
                return _pk_idHotel;
            }
            set
            {
                if (_pk_idHotel != value)
                {
                    Onpk_idHotelChanging(value);
                    ReportPropertyChanging("pk_idHotel");
                    _pk_idHotel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_idHotel");
                    Onpk_idHotelChanged();
                }
            }
        }
        private global::System.Int64 _pk_idHotel;
        partial void Onpk_idHotelChanging(global::System.Int64 value);
        partial void Onpk_idHotelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone1
        {
            get
            {
                return _phone1;
            }
            set
            {
                Onphone1Changing(value);
                ReportPropertyChanging("phone1");
                _phone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone1");
                Onphone1Changed();
            }
        }
        private global::System.String _phone1;
        partial void Onphone1Changing(global::System.String value);
        partial void Onphone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone2
        {
            get
            {
                return _phone2;
            }
            set
            {
                Onphone2Changing(value);
                ReportPropertyChanging("phone2");
                _phone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone2");
                Onphone2Changed();
            }
        }
        private global::System.String _phone2;
        partial void Onphone2Changing(global::System.String value);
        partial void Onphone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_idTown
        {
            get
            {
                return _fk_idTown;
            }
            set
            {
                Onfk_idTownChanging(value);
                ReportPropertyChanging("fk_idTown");
                _fk_idTown = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_idTown");
                Onfk_idTownChanged();
            }
        }
        private global::System.Int64 _fk_idTown;
        partial void Onfk_idTownChanging(global::System.Int64 value);
        partial void Onfk_idTownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagesDirectory
        {
            get
            {
                return _imagesDirectory;
            }
            set
            {
                OnimagesDirectoryChanging(value);
                ReportPropertyChanging("imagesDirectory");
                _imagesDirectory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imagesDirectory");
                OnimagesDirectoryChanged();
            }
        }
        private global::System.String _imagesDirectory;
        partial void OnimagesDirectoryChanging(global::System.String value);
        partial void OnimagesDirectoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String coverImage
        {
            get
            {
                return _coverImage;
            }
            set
            {
                OncoverImageChanging(value);
                ReportPropertyChanging("coverImage");
                _coverImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("coverImage");
                OncoverImageChanged();
            }
        }
        private global::System.String _coverImage;
        partial void OncoverImageChanging(global::System.String value);
        partial void OncoverImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stars
        {
            get
            {
                return _stars;
            }
            set
            {
                OnstarsChanging(value);
                ReportPropertyChanging("stars");
                _stars = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stars");
                OnstarsChanged();
            }
        }
        private global::System.String _stars;
        partial void OnstarsChanging(global::System.String value);
        partial void OnstarsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.Boolean _state;
        partial void OnstateChanging(global::System.Boolean value);
        partial void OnstateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_Hotel_Town", "Town")]
        public Town Town
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Town>("DanicoModel.FK_Hotel_Town", "Town").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Town>("DanicoModel.FK_Hotel_Town", "Town").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Town> TownReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Town>("DanicoModel.FK_Hotel_Town", "Town");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Town>("DanicoModel.FK_Hotel_Town", "Town", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_HotelService_Hotel", "HotelService")]
        public EntityCollection<HotelService> HotelServices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HotelService>("DanicoModel.FK_HotelService_Hotel", "HotelService");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HotelService>("DanicoModel.FK_HotelService_Hotel", "HotelService", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_TripType_Hotel", "TripType")]
        public EntityCollection<TripType> TripTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TripType>("DanicoModel.FK_TripType_Hotel", "TripType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TripType>("DanicoModel.FK_TripType_Hotel", "TripType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="HotelService")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HotelService : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HotelService object.
        /// </summary>
        /// <param name="idHotel">Initial value of the idHotel property.</param>
        /// <param name="idService">Initial value of the idService property.</param>
        public static HotelService CreateHotelService(global::System.Int64 idHotel, global::System.Int64 idService)
        {
            HotelService hotelService = new HotelService();
            hotelService.idHotel = idHotel;
            hotelService.idService = idService;
            return hotelService;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idHotel
        {
            get
            {
                return _idHotel;
            }
            set
            {
                if (_idHotel != value)
                {
                    OnidHotelChanging(value);
                    ReportPropertyChanging("idHotel");
                    _idHotel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idHotel");
                    OnidHotelChanged();
                }
            }
        }
        private global::System.Int64 _idHotel;
        partial void OnidHotelChanging(global::System.Int64 value);
        partial void OnidHotelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idService
        {
            get
            {
                return _idService;
            }
            set
            {
                if (_idService != value)
                {
                    OnidServiceChanging(value);
                    ReportPropertyChanging("idService");
                    _idService = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idService");
                    OnidServiceChanged();
                }
            }
        }
        private global::System.Int64 _idService;
        partial void OnidServiceChanging(global::System.Int64 value);
        partial void OnidServiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Double> _price;
        partial void OnpriceChanging(Nullable<global::System.Double> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagesDirectory
        {
            get
            {
                return _imagesDirectory;
            }
            set
            {
                OnimagesDirectoryChanging(value);
                ReportPropertyChanging("imagesDirectory");
                _imagesDirectory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imagesDirectory");
                OnimagesDirectoryChanged();
            }
        }
        private global::System.String _imagesDirectory;
        partial void OnimagesDirectoryChanging(global::System.String value);
        partial void OnimagesDirectoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> idRoom
        {
            get
            {
                return _idRoom;
            }
            set
            {
                OnidRoomChanging(value);
                ReportPropertyChanging("idRoom");
                _idRoom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idRoom");
                OnidRoomChanged();
            }
        }
        private Nullable<global::System.Int64> _idRoom;
        partial void OnidRoomChanging(Nullable<global::System.Int64> value);
        partial void OnidRoomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String coverImage1
        {
            get
            {
                return _coverImage1;
            }
            set
            {
                OncoverImage1Changing(value);
                ReportPropertyChanging("coverImage1");
                _coverImage1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("coverImage1");
                OncoverImage1Changed();
            }
        }
        private global::System.String _coverImage1;
        partial void OncoverImage1Changing(global::System.String value);
        partial void OncoverImage1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String coverImage2
        {
            get
            {
                return _coverImage2;
            }
            set
            {
                OncoverImage2Changing(value);
                ReportPropertyChanging("coverImage2");
                _coverImage2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("coverImage2");
                OncoverImage2Changed();
            }
        }
        private global::System.String _coverImage2;
        partial void OncoverImage2Changing(global::System.String value);
        partial void OncoverImage2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String coverImage0
        {
            get
            {
                return _coverImage0;
            }
            set
            {
                OncoverImage0Changing(value);
                ReportPropertyChanging("coverImage0");
                _coverImage0 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("coverImage0");
                OncoverImage0Changed();
            }
        }
        private global::System.String _coverImage0;
        partial void OncoverImage0Changing(global::System.String value);
        partial void OncoverImage0Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_HotelService_Hotel", "Hotel")]
        public Hotel Hotel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("DanicoModel.FK_HotelService_Hotel", "Hotel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("DanicoModel.FK_HotelService_Hotel", "Hotel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hotel> HotelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("DanicoModel.FK_HotelService_Hotel", "Hotel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hotel>("DanicoModel.FK_HotelService_Hotel", "Hotel", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_HotelService_Room", "Room")]
        public Room Room
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Room>("DanicoModel.FK_HotelService_Room", "Room").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Room>("DanicoModel.FK_HotelService_Room", "Room").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Room> RoomReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Room>("DanicoModel.FK_HotelService_Room", "Room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Room>("DanicoModel.FK_HotelService_Room", "Room", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_HotelService_Service", "Service")]
        public Service Service
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Service>("DanicoModel.FK_HotelService_Service", "Service").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Service>("DanicoModel.FK_HotelService_Service", "Service").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Service> ServiceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Service>("DanicoModel.FK_HotelService_Service", "Service");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Service>("DanicoModel.FK_HotelService_Service", "Service", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="Room")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Room : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Room object.
        /// </summary>
        /// <param name="pkidHabitacion">Initial value of the pkidHabitacion property.</param>
        public static Room CreateRoom(global::System.Int64 pkidHabitacion)
        {
            Room room = new Room();
            room.pkidHabitacion = pkidHabitacion;
            return room;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pkidHabitacion
        {
            get
            {
                return _pkidHabitacion;
            }
            set
            {
                if (_pkidHabitacion != value)
                {
                    OnpkidHabitacionChanging(value);
                    ReportPropertyChanging("pkidHabitacion");
                    _pkidHabitacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pkidHabitacion");
                    OnpkidHabitacionChanged();
                }
            }
        }
        private global::System.Int64 _pkidHabitacion;
        partial void OnpkidHabitacionChanging(global::System.Int64 value);
        partial void OnpkidHabitacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_HotelService_Room", "HotelService")]
        public EntityCollection<HotelService> HotelServices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HotelService>("DanicoModel.FK_HotelService_Room", "HotelService");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HotelService>("DanicoModel.FK_HotelService_Room", "HotelService", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="Service")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Service : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Service object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="pk_idService">Initial value of the pk_idService property.</param>
        public static Service CreateService(global::System.String name, global::System.String type, global::System.Int64 pk_idService)
        {
            Service service = new Service();
            service.name = name;
            service.type = type;
            service.pk_idService = pk_idService;
            return service;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pk_idService
        {
            get
            {
                return _pk_idService;
            }
            set
            {
                if (_pk_idService != value)
                {
                    Onpk_idServiceChanging(value);
                    ReportPropertyChanging("pk_idService");
                    _pk_idService = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_idService");
                    Onpk_idServiceChanged();
                }
            }
        }
        private global::System.Int64 _pk_idService;
        partial void Onpk_idServiceChanging(global::System.Int64 value);
        partial void Onpk_idServiceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_HotelService_Service", "HotelService")]
        public EntityCollection<HotelService> HotelServices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HotelService>("DanicoModel.FK_HotelService_Service", "HotelService");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HotelService>("DanicoModel.FK_HotelService_Service", "HotelService", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="Town")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Town : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Town object.
        /// </summary>
        /// <param name="pk_idTown">Initial value of the pk_idTown property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Town CreateTown(global::System.Int64 pk_idTown, global::System.String name)
        {
            Town town = new Town();
            town.pk_idTown = pk_idTown;
            town.name = name;
            return town;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pk_idTown
        {
            get
            {
                return _pk_idTown;
            }
            set
            {
                if (_pk_idTown != value)
                {
                    Onpk_idTownChanging(value);
                    ReportPropertyChanging("pk_idTown");
                    _pk_idTown = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_idTown");
                    Onpk_idTownChanged();
                }
            }
        }
        private global::System.Int64 _pk_idTown;
        partial void Onpk_idTownChanging(global::System.Int64 value);
        partial void Onpk_idTownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_Hotel_Town", "Hotel")]
        public EntityCollection<Hotel> Hotels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hotel>("DanicoModel.FK_Hotel_Town", "Hotel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hotel>("DanicoModel.FK_Hotel_Town", "Hotel", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="TripType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TripType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TripType object.
        /// </summary>
        /// <param name="idHotel">Initial value of the idHotel property.</param>
        /// <param name="family">Initial value of the family property.</param>
        /// <param name="couple">Initial value of the couple property.</param>
        /// <param name="friends">Initial value of the friends property.</param>
        /// <param name="lonely">Initial value of the lonely property.</param>
        /// <param name="groups">Initial value of the groups property.</param>
        /// <param name="transit">Initial value of the transit property.</param>
        /// <param name="business">Initial value of the business property.</param>
        public static TripType CreateTripType(global::System.Int64 idHotel, global::System.Boolean family, global::System.Boolean couple, global::System.Boolean friends, global::System.Boolean lonely, global::System.Boolean groups, global::System.Boolean transit, global::System.Boolean business)
        {
            TripType tripType = new TripType();
            tripType.idHotel = idHotel;
            tripType.family = family;
            tripType.couple = couple;
            tripType.friends = friends;
            tripType.lonely = lonely;
            tripType.groups = groups;
            tripType.transit = transit;
            tripType.business = business;
            return tripType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idHotel
        {
            get
            {
                return _idHotel;
            }
            set
            {
                if (_idHotel != value)
                {
                    OnidHotelChanging(value);
                    ReportPropertyChanging("idHotel");
                    _idHotel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idHotel");
                    OnidHotelChanged();
                }
            }
        }
        private global::System.Int64 _idHotel;
        partial void OnidHotelChanging(global::System.Int64 value);
        partial void OnidHotelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean family
        {
            get
            {
                return _family;
            }
            set
            {
                if (_family != value)
                {
                    OnfamilyChanging(value);
                    ReportPropertyChanging("family");
                    _family = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("family");
                    OnfamilyChanged();
                }
            }
        }
        private global::System.Boolean _family;
        partial void OnfamilyChanging(global::System.Boolean value);
        partial void OnfamilyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean couple
        {
            get
            {
                return _couple;
            }
            set
            {
                if (_couple != value)
                {
                    OncoupleChanging(value);
                    ReportPropertyChanging("couple");
                    _couple = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("couple");
                    OncoupleChanged();
                }
            }
        }
        private global::System.Boolean _couple;
        partial void OncoupleChanging(global::System.Boolean value);
        partial void OncoupleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean friends
        {
            get
            {
                return _friends;
            }
            set
            {
                if (_friends != value)
                {
                    OnfriendsChanging(value);
                    ReportPropertyChanging("friends");
                    _friends = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("friends");
                    OnfriendsChanged();
                }
            }
        }
        private global::System.Boolean _friends;
        partial void OnfriendsChanging(global::System.Boolean value);
        partial void OnfriendsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean lonely
        {
            get
            {
                return _lonely;
            }
            set
            {
                if (_lonely != value)
                {
                    OnlonelyChanging(value);
                    ReportPropertyChanging("lonely");
                    _lonely = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("lonely");
                    OnlonelyChanged();
                }
            }
        }
        private global::System.Boolean _lonely;
        partial void OnlonelyChanging(global::System.Boolean value);
        partial void OnlonelyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean groups
        {
            get
            {
                return _groups;
            }
            set
            {
                if (_groups != value)
                {
                    OngroupsChanging(value);
                    ReportPropertyChanging("groups");
                    _groups = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("groups");
                    OngroupsChanged();
                }
            }
        }
        private global::System.Boolean _groups;
        partial void OngroupsChanging(global::System.Boolean value);
        partial void OngroupsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean transit
        {
            get
            {
                return _transit;
            }
            set
            {
                if (_transit != value)
                {
                    OntransitChanging(value);
                    ReportPropertyChanging("transit");
                    _transit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("transit");
                    OntransitChanged();
                }
            }
        }
        private global::System.Boolean _transit;
        partial void OntransitChanging(global::System.Boolean value);
        partial void OntransitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean business
        {
            get
            {
                return _business;
            }
            set
            {
                if (_business != value)
                {
                    OnbusinessChanging(value);
                    ReportPropertyChanging("business");
                    _business = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("business");
                    OnbusinessChanged();
                }
            }
        }
        private global::System.Boolean _business;
        partial void OnbusinessChanging(global::System.Boolean value);
        partial void OnbusinessChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DanicoModel", "FK_TripType_Hotel", "Hotel")]
        public Hotel Hotel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("DanicoModel.FK_TripType_Hotel", "Hotel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("DanicoModel.FK_TripType_Hotel", "Hotel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hotel> HotelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hotel>("DanicoModel.FK_TripType_Hotel", "Hotel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hotel>("DanicoModel.FK_TripType_Hotel", "Hotel", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="vHotel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vHotel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vHotel object.
        /// </summary>
        /// <param name="hpk_idHotel">Initial value of the Hpk_idHotel property.</param>
        public static vHotel CreatevHotel(global::System.Int64 hpk_idHotel)
        {
            vHotel vHotel = new vHotel();
            vHotel.Hpk_idHotel = hpk_idHotel;
            return vHotel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Hpk_idHotel
        {
            get
            {
                return _Hpk_idHotel;
            }
            set
            {
                if (_Hpk_idHotel != value)
                {
                    OnHpk_idHotelChanging(value);
                    ReportPropertyChanging("Hpk_idHotel");
                    _Hpk_idHotel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Hpk_idHotel");
                    OnHpk_idHotelChanged();
                }
            }
        }
        private global::System.Int64 _Hpk_idHotel;
        partial void OnHpk_idHotelChanging(global::System.Int64 value);
        partial void OnHpk_idHotelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hname
        {
            get
            {
                return _Hname;
            }
            set
            {
                OnHnameChanging(value);
                ReportPropertyChanging("Hname");
                _Hname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hname");
                OnHnameChanged();
            }
        }
        private global::System.String _Hname;
        partial void OnHnameChanging(global::System.String value);
        partial void OnHnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Haddress
        {
            get
            {
                return _Haddress;
            }
            set
            {
                OnHaddressChanging(value);
                ReportPropertyChanging("Haddress");
                _Haddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Haddress");
                OnHaddressChanged();
            }
        }
        private global::System.String _Haddress;
        partial void OnHaddressChanging(global::System.String value);
        partial void OnHaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hdescription
        {
            get
            {
                return _Hdescription;
            }
            set
            {
                OnHdescriptionChanging(value);
                ReportPropertyChanging("Hdescription");
                _Hdescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hdescription");
                OnHdescriptionChanged();
            }
        }
        private global::System.String _Hdescription;
        partial void OnHdescriptionChanging(global::System.String value);
        partial void OnHdescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hphone1
        {
            get
            {
                return _Hphone1;
            }
            set
            {
                OnHphone1Changing(value);
                ReportPropertyChanging("Hphone1");
                _Hphone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hphone1");
                OnHphone1Changed();
            }
        }
        private global::System.String _Hphone1;
        partial void OnHphone1Changing(global::System.String value);
        partial void OnHphone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hphone2
        {
            get
            {
                return _Hphone2;
            }
            set
            {
                OnHphone2Changing(value);
                ReportPropertyChanging("Hphone2");
                _Hphone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hphone2");
                OnHphone2Changed();
            }
        }
        private global::System.String _Hphone2;
        partial void OnHphone2Changing(global::System.String value);
        partial void OnHphone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hemail
        {
            get
            {
                return _Hemail;
            }
            set
            {
                OnHemailChanging(value);
                ReportPropertyChanging("Hemail");
                _Hemail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hemail");
                OnHemailChanged();
            }
        }
        private global::System.String _Hemail;
        partial void OnHemailChanging(global::System.String value);
        partial void OnHemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Hfk_idTown
        {
            get
            {
                return _Hfk_idTown;
            }
            set
            {
                OnHfk_idTownChanging(value);
                ReportPropertyChanging("Hfk_idTown");
                _Hfk_idTown = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hfk_idTown");
                OnHfk_idTownChanged();
            }
        }
        private Nullable<global::System.Int64> _Hfk_idTown;
        partial void OnHfk_idTownChanging(Nullable<global::System.Int64> value);
        partial void OnHfk_idTownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HimagesDirectory
        {
            get
            {
                return _HimagesDirectory;
            }
            set
            {
                OnHimagesDirectoryChanging(value);
                ReportPropertyChanging("HimagesDirectory");
                _HimagesDirectory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HimagesDirectory");
                OnHimagesDirectoryChanged();
            }
        }
        private global::System.String _HimagesDirectory;
        partial void OnHimagesDirectoryChanging(global::System.String value);
        partial void OnHimagesDirectoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HcoverImage
        {
            get
            {
                return _HcoverImage;
            }
            set
            {
                OnHcoverImageChanging(value);
                ReportPropertyChanging("HcoverImage");
                _HcoverImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HcoverImage");
                OnHcoverImageChanged();
            }
        }
        private global::System.String _HcoverImage;
        partial void OnHcoverImageChanging(global::System.String value);
        partial void OnHcoverImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hstars
        {
            get
            {
                return _Hstars;
            }
            set
            {
                OnHstarsChanging(value);
                ReportPropertyChanging("Hstars");
                _Hstars = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hstars");
                OnHstarsChanged();
            }
        }
        private global::System.String _Hstars;
        partial void OnHstarsChanging(global::System.String value);
        partial void OnHstarsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Hstate
        {
            get
            {
                return _Hstate;
            }
            set
            {
                OnHstateChanging(value);
                ReportPropertyChanging("Hstate");
                _Hstate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hstate");
                OnHstateChanged();
            }
        }
        private Nullable<global::System.Boolean> _Hstate;
        partial void OnHstateChanging(Nullable<global::System.Boolean> value);
        partial void OnHstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> HSidHotel
        {
            get
            {
                return _HSidHotel;
            }
            set
            {
                OnHSidHotelChanging(value);
                ReportPropertyChanging("HSidHotel");
                _HSidHotel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HSidHotel");
                OnHSidHotelChanged();
            }
        }
        private Nullable<global::System.Int64> _HSidHotel;
        partial void OnHSidHotelChanging(Nullable<global::System.Int64> value);
        partial void OnHSidHotelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> HSidService
        {
            get
            {
                return _HSidService;
            }
            set
            {
                OnHSidServiceChanging(value);
                ReportPropertyChanging("HSidService");
                _HSidService = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HSidService");
                OnHSidServiceChanged();
            }
        }
        private Nullable<global::System.Int64> _HSidService;
        partial void OnHSidServiceChanging(Nullable<global::System.Int64> value);
        partial void OnHSidServiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> HSprice
        {
            get
            {
                return _HSprice;
            }
            set
            {
                OnHSpriceChanging(value);
                ReportPropertyChanging("HSprice");
                _HSprice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HSprice");
                OnHSpriceChanged();
            }
        }
        private Nullable<global::System.Double> _HSprice;
        partial void OnHSpriceChanging(Nullable<global::System.Double> value);
        partial void OnHSpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HSdescription
        {
            get
            {
                return _HSdescription;
            }
            set
            {
                OnHSdescriptionChanging(value);
                ReportPropertyChanging("HSdescription");
                _HSdescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HSdescription");
                OnHSdescriptionChanged();
            }
        }
        private global::System.String _HSdescription;
        partial void OnHSdescriptionChanging(global::System.String value);
        partial void OnHSdescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HSimagesDirectory
        {
            get
            {
                return _HSimagesDirectory;
            }
            set
            {
                OnHSimagesDirectoryChanging(value);
                ReportPropertyChanging("HSimagesDirectory");
                _HSimagesDirectory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HSimagesDirectory");
                OnHSimagesDirectoryChanged();
            }
        }
        private global::System.String _HSimagesDirectory;
        partial void OnHSimagesDirectoryChanging(global::System.String value);
        partial void OnHSimagesDirectoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HScoverImage0
        {
            get
            {
                return _HScoverImage0;
            }
            set
            {
                OnHScoverImage0Changing(value);
                ReportPropertyChanging("HScoverImage0");
                _HScoverImage0 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HScoverImage0");
                OnHScoverImage0Changed();
            }
        }
        private global::System.String _HScoverImage0;
        partial void OnHScoverImage0Changing(global::System.String value);
        partial void OnHScoverImage0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HScoverImage1
        {
            get
            {
                return _HScoverImage1;
            }
            set
            {
                OnHScoverImage1Changing(value);
                ReportPropertyChanging("HScoverImage1");
                _HScoverImage1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HScoverImage1");
                OnHScoverImage1Changed();
            }
        }
        private global::System.String _HScoverImage1;
        partial void OnHScoverImage1Changing(global::System.String value);
        partial void OnHScoverImage1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HScoverImage2
        {
            get
            {
                return _HScoverImage2;
            }
            set
            {
                OnHScoverImage2Changing(value);
                ReportPropertyChanging("HScoverImage2");
                _HScoverImage2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HScoverImage2");
                OnHScoverImage2Changed();
            }
        }
        private global::System.String _HScoverImage2;
        partial void OnHScoverImage2Changing(global::System.String value);
        partial void OnHScoverImage2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> HSidRoom
        {
            get
            {
                return _HSidRoom;
            }
            set
            {
                OnHSidRoomChanging(value);
                ReportPropertyChanging("HSidRoom");
                _HSidRoom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HSidRoom");
                OnHSidRoomChanged();
            }
        }
        private Nullable<global::System.Int64> _HSidRoom;
        partial void OnHSidRoomChanging(Nullable<global::System.Int64> value);
        partial void OnHSidRoomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sname
        {
            get
            {
                return _Sname;
            }
            set
            {
                OnSnameChanging(value);
                ReportPropertyChanging("Sname");
                _Sname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sname");
                OnSnameChanged();
            }
        }
        private global::System.String _Sname;
        partial void OnSnameChanging(global::System.String value);
        partial void OnSnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stype
        {
            get
            {
                return _Stype;
            }
            set
            {
                OnStypeChanging(value);
                ReportPropertyChanging("Stype");
                _Stype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stype");
                OnStypeChanged();
            }
        }
        private global::System.String _Stype;
        partial void OnStypeChanging(global::System.String value);
        partial void OnStypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Spk_idService
        {
            get
            {
                return _Spk_idService;
            }
            set
            {
                OnSpk_idServiceChanging(value);
                ReportPropertyChanging("Spk_idService");
                _Spk_idService = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Spk_idService");
                OnSpk_idServiceChanged();
            }
        }
        private Nullable<global::System.Int64> _Spk_idService;
        partial void OnSpk_idServiceChanging(Nullable<global::System.Int64> value);
        partial void OnSpk_idServiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RpkidHabitacion
        {
            get
            {
                return _RpkidHabitacion;
            }
            set
            {
                OnRpkidHabitacionChanging(value);
                ReportPropertyChanging("RpkidHabitacion");
                _RpkidHabitacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RpkidHabitacion");
                OnRpkidHabitacionChanged();
            }
        }
        private Nullable<global::System.Int64> _RpkidHabitacion;
        partial void OnRpkidHabitacionChanging(Nullable<global::System.Int64> value);
        partial void OnRpkidHabitacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rtype
        {
            get
            {
                return _Rtype;
            }
            set
            {
                OnRtypeChanging(value);
                ReportPropertyChanging("Rtype");
                _Rtype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rtype");
                OnRtypeChanged();
            }
        }
        private global::System.String _Rtype;
        partial void OnRtypeChanging(global::System.String value);
        partial void OnRtypeChanged();

        #endregion
    
    }

    #endregion
    
}
