//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DanicoProject.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DanicoCon : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DanicoCon usando la cadena de conexión encontrada en la sección 'DanicoCon' del archivo de configuración de la aplicación.
        /// </summary>
        public DanicoCon() : base("name=DanicoCon", "DanicoCon")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DanicoCon.
        /// </summary>
        public DanicoCon(string connectionString) : base(connectionString, "DanicoCon")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DanicoCon.
        /// </summary>
        public DanicoCon(EntityConnection connection) : base(connection, "DanicoCon")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Hotel1> Hotels
        {
            get
            {
                if ((_Hotels == null))
                {
                    _Hotels = base.CreateObjectSet<Hotel1>("Hotels");
                }
                return _Hotels;
            }
        }
        private ObjectSet<Hotel1> _Hotels;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Hotels. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToHotels(Hotel1 hotel1)
        {
            base.AddObject("Hotels", hotel1);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DanicoModel", Name="Hotel1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hotel1 : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Hotel1.
        /// </summary>
        /// <param name="pk_idHotel">Valor inicial de la propiedad pk_idHotel.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="address">Valor inicial de la propiedad address.</param>
        /// <param name="description">Valor inicial de la propiedad description.</param>
        /// <param name="fk_idTown">Valor inicial de la propiedad fk_idTown.</param>
        public static Hotel1 CreateHotel1(global::System.Int64 pk_idHotel, global::System.String name, global::System.String address, global::System.String description, global::System.Int64 fk_idTown)
        {
            Hotel1 hotel1 = new Hotel1();
            hotel1.pk_idHotel = pk_idHotel;
            hotel1.name = name;
            hotel1.address = address;
            hotel1.description = description;
            hotel1.fk_idTown = fk_idTown;
            return hotel1;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pk_idHotel
        {
            get
            {
                return _pk_idHotel;
            }
            set
            {
                if (_pk_idHotel != value)
                {
                    Onpk_idHotelChanging(value);
                    ReportPropertyChanging("pk_idHotel");
                    _pk_idHotel = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_idHotel");
                    Onpk_idHotelChanged();
                }
            }
        }
        private global::System.Int64 _pk_idHotel;
        partial void Onpk_idHotelChanging(global::System.Int64 value);
        partial void Onpk_idHotelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone1
        {
            get
            {
                return _phone1;
            }
            set
            {
                Onphone1Changing(value);
                ReportPropertyChanging("phone1");
                _phone1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone1");
                Onphone1Changed();
            }
        }
        private global::System.String _phone1;
        partial void Onphone1Changing(global::System.String value);
        partial void Onphone1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone2
        {
            get
            {
                return _phone2;
            }
            set
            {
                Onphone2Changing(value);
                ReportPropertyChanging("phone2");
                _phone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone2");
                Onphone2Changed();
            }
        }
        private global::System.String _phone2;
        partial void Onphone2Changing(global::System.String value);
        partial void Onphone2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_idTown
        {
            get
            {
                return _fk_idTown;
            }
            set
            {
                Onfk_idTownChanging(value);
                ReportPropertyChanging("fk_idTown");
                _fk_idTown = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_idTown");
                Onfk_idTownChanged();
            }
        }
        private global::System.Int64 _fk_idTown;
        partial void Onfk_idTownChanging(global::System.Int64 value);
        partial void Onfk_idTownChanged();

        #endregion
    
    }

    #endregion
    
}
