//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DanicoProject.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DanicoEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DanicoEntities usando la cadena de conexión encontrada en la sección 'DanicoEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public DanicoEntities() : base("name=DanicoEntities", "DanicoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DanicoEntities.
        /// </summary>
        public DanicoEntities(string connectionString) : base(connectionString, "DanicoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DanicoEntities.
        /// </summary>
        public DanicoEntities(EntityConnection connection) : base(connection, "DanicoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Town1> Towns
        {
            get
            {
                if ((_Towns == null))
                {
                    _Towns = base.CreateObjectSet<Town1>("Towns");
                }
                return _Towns;
            }
        }
        private ObjectSet<Town1> _Towns;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Towns. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTowns(Town1 town1)
        {
            base.AddObject("Towns", town1);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="townEntity", Name="Town1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Town1 : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Town1.
        /// </summary>
        /// <param name="pk_idTown">Valor inicial de la propiedad pk_idTown.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        public static Town1 CreateTown1(global::System.Int64 pk_idTown, global::System.String name)
        {
            Town1 town1 = new Town1();
            town1.pk_idTown = pk_idTown;
            town1.name = name;
            return town1;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 pk_idTown
        {
            get
            {
                return _pk_idTown;
            }
            set
            {
                if (_pk_idTown != value)
                {
                    Onpk_idTownChanging(value);
                    ReportPropertyChanging("pk_idTown");
                    _pk_idTown = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pk_idTown");
                    Onpk_idTownChanged();
                }
            }
        }
        private global::System.Int64 _pk_idTown;
        partial void Onpk_idTownChanging(global::System.Int64 value);
        partial void Onpk_idTownChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }

    #endregion
    
}
