
insert into Town values ('Santafé de Bogotá')	   
insert into Town values ('Puerto Nariño')	   
insert into Town values ('Leticia')	   
insert into Town values ('Medellín')	   
insert into Town values ('Abejorral')	   
insert into Town values ('Abriaqui')	   
insert into Town values ('Alejandría')	   
insert into Town values ('Amagá')	   
insert into Town values ('Amalfi')	   
insert into Town values ('Andes')	   
insert into Town values ('Angelópolis')	   
insert into Town values ('Angostura')	   
insert into Town values ('Anorí')	   
insert into Town values ('Antioquia')	   
insert into Town values ('Anza')	   
insert into Town values ('Apartadó')	   
insert into Town values ('Arboletes')	   
insert into Town values ('Argelia')	   
insert into Town values ('Armenia')	   
insert into Town values ('Barbosa')	   
insert into Town values ('Belmira')	   
insert into Town values ('Bello')	   
insert into Town values ('Betania')	   
insert into Town values ('Betulia')	   
insert into Town values ('Bolívar')	   
insert into Town values ('Briseño')	   
insert into Town values ('Buriticá')	   
insert into Town values ('Cáceres')	   
insert into Town values ('Caicedo')	   
insert into Town values ('Caldas')	   
insert into Town values ('Campamento')	   
insert into Town values ('Cañasgordas')	   
insert into Town values ('Caracolí')	   
insert into Town values ('Caramanta')	   
insert into Town values ('Carepa')	   
insert into Town values ('Carmen de Viboral')	   
insert into Town values ('Carolina')	   
insert into Town values ('Caucasia')	   
insert into Town values ('Chigorodó')	   
insert into Town values ('Cisneros')	   
insert into Town values ('Cocorná')	   
insert into Town values ('Concepción')	   
insert into Town values ('Concordia')	   
insert into Town values ('Copacabana')	   
insert into Town values ('Dabeiba')	   
insert into Town values ('Don Matías')	   
insert into Town values ('Ebéjico')	   
insert into Town values ('El Bagre')	   
insert into Town values ('Entrerríos')	   
insert into Town values ('Envigado')	   
insert into Town values ('Fredonia')	   
insert into Town values ('Frontino')	   
insert into Town values ('Giraldo')	   
insert into Town values ('Girardota')	   
insert into Town values ('Gómez Plata')	   
insert into Town values ('Granada')	   
insert into Town values ('Guadalupe')	   
insert into Town values ('Guarne')	   
insert into Town values ('Guatapé')	   
insert into Town values ('Heliconia')	   
insert into Town values ('Hispania')	   
insert into Town values ('Itagüí')	   
insert into Town values ('Ituango')	   
insert into Town values ('Jardín')	   
insert into Town values ('Jericó')	   
insert into Town values ('La Ceja')	   
insert into Town values ('La Estrella')	   
insert into Town values ('La Pintada')	   
insert into Town values ('La Unión')	   
insert into Town values ('Liborina')	   
insert into Town values ('Maceo')	   
insert into Town values ('Marinilla')	   
insert into Town values ('Montebello')	   
insert into Town values ('Murindó')	   
insert into Town values ('Mutatá')	   
insert into Town values ('Nariño')	   
insert into Town values ('Necoclí')	   
insert into Town values ('Nechí')	   
insert into Town values ('Olaya')	   
insert into Town values ('Peñol')	   
insert into Town values ('Peque')	   
insert into Town values ('Pueblorrico')	   
insert into Town values ('Puerto Berrío')	   
insert into Town values ('Puerto Nare')	   
insert into Town values ('Puerto Triunfo')	   
insert into Town values ('Remedios')	   
insert into Town values ('Retiro')	   
insert into Town values ('Rionegro')	   
insert into Town values ('Sabanalarga')	   
insert into Town values ('Sabaneta')	   
insert into Town values ('Salgar')	   
insert into Town values ('San Andrés')	   
insert into Town values ('San Carlos')	   
insert into Town values ('San francisco')	   
insert into Town values ('San Jerónimo')	   
insert into Town values ('San José de Montaña')	   
insert into Town values ('San Juan de Urabá')	   
insert into Town values ('San Luis')	   
insert into Town values ('San Pedro')	   
insert into Town values ('San Pedro de Urabá')	   
insert into Town values ('San Rafael')	   
insert into Town values ('San Roque')	   
insert into Town values ('San Vicente')	   
insert into Town values ('Santa Bárbara')	   
insert into Town values ('Santa Rosa de Osos')	   
insert into Town values ('Santo Domingo')	   
insert into Town values ('Santuario')	   
insert into Town values ('Segovia')	   
insert into Town values ('Sonsón')	   
insert into Town values ('Sopetrán')	   
insert into Town values ('Támesis')	   
insert into Town values ('Tarazá')	   
insert into Town values ('Tarso')	   
insert into Town values ('Titiribí')	   
insert into Town values ('Toledo')	   
insert into Town values ('Turbo')	   
insert into Town values ('Uramita')	   
insert into Town values ('Urrao')	   
insert into Town values ('Valdivia')	   
insert into Town values ('Valparaíso')	   
insert into Town values ('Vegachi')	   
insert into Town values ('Venecia')	   
insert into Town values ('Vigía del Fuerte')	   
insert into Town values ('Yalí')	   
insert into Town values ('Yarumal')	   
insert into Town values ('Yolombó')	   
insert into Town values ('Yondó (Casabe')	   
insert into Town values ('Zaragoza 895')	   
insert into Town values ('Arauca')	   
insert into Town values ('Arauquita')	   
insert into Town values ('Cravo Norte')	   
insert into Town values ('Fortul')	   
insert into Town values ('Puerto Rondón')	   
insert into Town values ('Fortul')	   
insert into Town values ('Puerto Rondón')	   
insert into Town values ('Saravena')	   
insert into Town values ('Tame')	   
insert into Town values ('Barranquilla')	   
insert into Town values ('Baranoa')	   
insert into Town values ('Campo de la Cruz')	   
insert into Town values ('Candelaria')	   
insert into Town values ('Galapa')	   
insert into Town values ('Juan de Acosta')	   
insert into Town values ('Luruaco')	   
insert into Town values ('Malambo')	   
insert into Town values ('Manatí')	   
insert into Town values ('Palmar de Varela')	   
insert into Town values ('Piojó')	   
insert into Town values ('Polonuevo')	   
insert into Town values ('Ponedera')	   
insert into Town values ('Puerto Colombia')	   
insert into Town values ('Repelón')	   
insert into Town values ('Sabanagrande')	   
insert into Town values ('Sabanalarga')	   
insert into Town values ('Santa Lucía')	   
insert into Town values ('Santo Tomás')	   
insert into Town values ('Soledad')	   
insert into Town values ('Suan')	   
insert into Town values ('Tubara')	   
insert into Town values ('Usiacurí')	   
insert into Town values ('Cartagena')	   
insert into Town values ('Achí')	   
insert into Town values ('Altos del Rosario')	   
insert into Town values ('Arenal')	   
insert into Town values ('Arjona')	   
insert into Town values ('Arroyohondo')	   
insert into Town values ('Barranco de Loba')	   
insert into Town values ('Calamar')	   
insert into Town values ('Cantagallo')	   
insert into Town values ('Cicuto')	   
insert into Town values ('Córdoba')	   
insert into Town values ('Clemencia')	   
insert into Town values ('El Carmen de Bolívar')	   
insert into Town values ('El Guamo')	   
insert into Town values ('El Peñón')	   
insert into Town values ('Hatillo de Loba')	   
insert into Town values ('Magangue')	   
insert into Town values ('Mahates')	   
insert into Town values ('Margarita')	   
insert into Town values ('María la Baja')	   
insert into Town values ('Montecristo')	   
insert into Town values ('Mompós')	   
insert into Town values ('Morales')	   
insert into Town values ('Pinillos')	   
insert into Town values ('Regidor')	   
insert into Town values ('Río Viejo')	   
insert into Town values ('San Cristóbal')	   
insert into Town values ('San Estanislao')	   
insert into Town values ('San Fernando')	   
insert into Town values ('San Jacinto')	   
insert into Town values ('San Jacinto del Cauca')	   
insert into Town values ('San Juan Nepomuceno')	   
insert into Town values ('San Martín de Loba')	   
insert into Town values ('San Pablo')	   
insert into Town values ('Santa Catalina')	   
insert into Town values ('Santa Rosa')	   
insert into Town values ('Santa Rosa del Sur')	   
insert into Town values ('Simití')	   
insert into Town values ('Soplaviento')	   
insert into Town values ('Talaigua Nuevo')	   
insert into Town values ('Tiquisio (Puerto Rico')	   
insert into Town values ('Turbaco')	   
insert into Town values ('Turbaná')	   
insert into Town values ('Villanueva')	   
insert into Town values ('Zambrano')	   
insert into Town values ('Tunja')	   
insert into Town values ('Almeida')	   
insert into Town values ('Aquitania')	   
insert into Town values ('Arcabuco')	   
insert into Town values ('Belén')	   
insert into Town values ('Berbeo')	   
insert into Town values ('Beteitiva')	   
insert into Town values ('Boavita')	   
insert into Town values ('Boyacá')	   
insert into Town values ('Briseño')	   
insert into Town values ('Buenavista')	   
insert into Town values ('Busbanza')	   
insert into Town values ('Caldas')	   
insert into Town values ('Campohermoso')	   
insert into Town values ('Cerinza')	   
insert into Town values ('Chinavita')	   
insert into Town values ('Chiquinquirá')	   
insert into Town values ('Chiscas')	   
insert into Town values ('Chita')	   
insert into Town values ('Chitaranque')	   
insert into Town values ('Chivata')	   
insert into Town values ('Ciénaga')	   
insert into Town values ('Combita')	   
insert into Town values ('Coper')	   
insert into Town values ('Corrales')	   
insert into Town values ('Covarachia')	   
insert into Town values ('Cubar')	   
insert into Town values ('Cucaita')	   
insert into Town values ('Cuitiva')	   
insert into Town values ('Chíquiza')	   
insert into Town values ('Chivor')	   
insert into Town values ('Duitama')	   
insert into Town values ('El Cocuy')	   
insert into Town values ('El Espino')	   
insert into Town values ('Firavitoba')	   
insert into Town values ('Floresta')	   
insert into Town values ('Gachantivá')	   
insert into Town values ('Gámeza')	   
insert into Town values ('Garagoa')	   
insert into Town values ('Guacamayas')	   
insert into Town values ('Guateque')	   
insert into Town values ('Guayatá')	   
insert into Town values ('Guicán')	   
insert into Town values ('Iza')	   
insert into Town values ('Jenesano')	   
insert into Town values ('Jericó')	   
insert into Town values ('Labranzagrande')	   
insert into Town values ('La Capilla')	   
insert into Town values ('La Victoria')	   
insert into Town values ('La Ubita')	   
insert into Town values ('Villa de Leyva')	   
insert into Town values ('Macanal')	   
insert into Town values ('Maripí')	   
insert into Town values ('Miraflores')	   
insert into Town values ('Mongua')	   
insert into Town values ('Monguí')	   
insert into Town values ('Moniquirá')	   
insert into Town values ('Motavita')	   
insert into Town values ('Muzo')	   
insert into Town values ('Nobsa')	   
insert into Town values ('Nuevo Colón')	   
insert into Town values ('Oicatá')	   
insert into Town values ('Otanche')	   
insert into Town values ('Pachavita')	   
insert into Town values ('Páez')	   
insert into Town values ('Paipa')	   
insert into Town values ('Pajarito')	   
insert into Town values ('Panqueba')	   
insert into Town values ('Pauna')	   
insert into Town values ('Paya')	   
insert into Town values ('Paz de Río')	   
insert into Town values ('Pesca')	   
insert into Town values ('Pisva')	   
insert into Town values ('Puerto Boyacá')	   
insert into Town values ('Quipama')	   
insert into Town values ('Ramiquirí')	   
insert into Town values ('Ráquira')	   
insert into Town values ('Rondón')	   
insert into Town values ('Saboyá')	   
insert into Town values ('Sáchica')	   
insert into Town values ('Samacá')	   
insert into Town values ('San Eduardo')	   
insert into Town values ('San José de Pare')	   
insert into Town values ('San Luis de Gaceno')	   
insert into Town values ('San Mateo')	   
insert into Town values ('San Miguel de Sema')	   
insert into Town values ('San Pablo de Borbur')	   
insert into Town values ('Santana')	   
insert into Town values ('Santa María')	   
insert into Town values ('Santa Rosa de Viterbo')	   
insert into Town values ('Santa Sofía')	   
insert into Town values ('Sativanorte')	   
insert into Town values ('Sativasur')	   
insert into Town values ('Siachoque')	   
insert into Town values ('Soatá')	   
insert into Town values ('Socotá')	   
insert into Town values ('Socha')	   
insert into Town values ('Sogamoso')	   
insert into Town values ('Somondoco')	   
insert into Town values ('Sora')	   
insert into Town values ('Sotaquirá')	   
insert into Town values ('Soracá')	   
insert into Town values ('Susacón')	   
insert into Town values ('Sutamarchán')	   
insert into Town values ('Sutatenza')	   
insert into Town values ('Tasco')	   
insert into Town values ('Tenza')	   
insert into Town values ('Tibaná')	   
insert into Town values ('Tibasosa')	   
insert into Town values ('Tinjacá')	   
insert into Town values ('Tipacoque')	   
insert into Town values ('Toca')	   
insert into Town values ('Toguí')	   
insert into Town values ('Topaga')	   
insert into Town values ('Tota')	   
insert into Town values ('Tunungua')	   
insert into Town values ('Turmequé')	   
insert into Town values ('Tuta')	   
insert into Town values ('Tutazá')	   
insert into Town values ('Umbita')	   
insert into Town values ('Ventaquemada')	   
insert into Town values ('Viracachá')	   
insert into Town values ('Zetaquirá')	   
insert into Town values ('Manizales')	   
insert into Town values ('Aguadas')	   
insert into Town values ('Anserma')	   
insert into Town values ('Aranzazu')	   
insert into Town values ('Belalcázar')	   
insert into Town values ('Chinchina')	   
insert into Town values ('Filadelfia')	   
insert into Town values ('La Dorada')	   
insert into Town values ('La Merced')	   
insert into Town values ('Manzanares')	   
insert into Town values ('Marmato')	   
insert into Town values ('Marquetalia')	   
insert into Town values ('Marulanda')	   
insert into Town values ('Neira')	   
insert into Town values ('Pácora')	   
insert into Town values ('Palestina')	   
insert into Town values ('Pensilvania')	   
insert into Town values ('Riosucio')	   
insert into Town values ('Risaralda')	   
insert into Town values ('Salamina')	   
insert into Town values ('Samaná')	   
insert into Town values ('San José')	   
insert into Town values ('Supía')	   
insert into Town values ('Victoria')	   
insert into Town values ('Villamaría')	   
insert into Town values ('Viterbo')	   
insert into Town values ('Caquetá 18 Florencia')	   
insert into Town values ('Albania')	   
insert into Town values ('Belén de los Andaquíes')	   
insert into Town values ('Cartagena del Chairá')	   
insert into Town values ('Curillo')	   
insert into Town values ('El Doncello')	   
insert into Town values ('El Paujil')	   
insert into Town values ('La Montañita')	   
insert into Town values ('Milán')	   
insert into Town values ('Morelia')	   
insert into Town values ('Puerto Rico')	   
insert into Town values ('San José del Fragua')	   
insert into Town values ('San Vicente del Caguán')	   
insert into Town values ('Solano')	   
insert into Town values ('Solita')	   
insert into Town values ('Valparaíso')	   
insert into Town values ('Yopal')	   
insert into Town values ('Aguazul')	   
insert into Town values ('Chameza')	   
insert into Town values ('Hato Corozal')	   
insert into Town values ('La Salina')	   
insert into Town values ('Maní')	   
insert into Town values ('Monterrey')	   
insert into Town values ('Nunchía')	   
insert into Town values ('Orocué')	   
insert into Town values ('Paz de Ariporo')	   
insert into Town values ('Pore')	   
insert into Town values ('Recetor')	   
insert into Town values ('Sabalarga')	   
insert into Town values ('Sacama')	   
insert into Town values ('San Luis de Palenque')	   
insert into Town values ('Támara')	   
insert into Town values ('Tauramena')	   
insert into Town values ('Trinidad')	   
insert into Town values ('Villanueva')	   
insert into Town values ('Popayán')	   
insert into Town values ('Almaguer')	   
insert into Town values ('Argelia')	   
insert into Town values ('Balboa')	   
insert into Town values ('Bolívar')	   
insert into Town values ('Buenos Aires')	   
insert into Town values ('Cajibío')	   
insert into Town values ('Caldono')	   
insert into Town values ('Caloto')	   
insert into Town values ('Corinto')	   
insert into Town values ('El Tambo')	   
insert into Town values ('Florencia')	   
insert into Town values ('Guapi')	   
insert into Town values ('Inzá')	   
insert into Town values ('Jambaló')	   
insert into Town values ('La Sierra')	   
insert into Town values ('La Vega')	   
insert into Town values ('López (Micay')
insert into Town values ('Mercaderes')	   
insert into Town values ('Miranda')	   
insert into Town values ('Morales')	   
insert into Town values ('Padilla')	   
insert into Town values ('Páez (Belalcazar')
insert into Town values ('Patía (El Bordo')	   
insert into Town values ('Piamonte')	   
insert into Town values ('Piendamó')	   
insert into Town values ('Puerto Tejada')	   
insert into Town values ('Puracé (Coconuco')	   
insert into Town values ('Rosas')	   
insert into Town values ('San Sebastián')	   
insert into Town values ('Santander de Quilichao')	   
insert into Town values ('Santa Rosa')	   
insert into Town values ('Silvia')	   
insert into Town values ('Sotara (Paispamba')   
insert into Town values ('Suárez')	   
insert into Town values ('Timbío')	   
insert into Town values ('Timbiquí')	   
insert into Town values ('Toribio')	   
insert into Town values ('Totoro')	   
insert into Town values ('Valledupar')	   
insert into Town values ('Aguachica')	   
insert into Town values ('Agustín Codazzi')	   
insert into Town values ('Astrea')	   
insert into Town values ('Becerril')	   
insert into Town values ('Bosconia')	   
insert into Town values ('Chimichagua')	   
insert into Town values ('Chiriguaná')	   
insert into Town values ('Curumaní')	   
insert into Town values ('El Copey')	   
insert into Town values ('El Paso')	   
insert into Town values ('Gamarra')	   
insert into Town values ('González')	   
insert into Town values ('La Gloria')	   
insert into Town values ('La Jagua de Ibirico')	   
insert into Town values ('Manaure Balcón Cesar')	   
insert into Town values ('Pailitas')	   
insert into Town values ('Pelaya')	   
insert into Town values ('Pueblo Bello')	   
insert into Town values ('Río de Oro')	   
insert into Town values ('La Paz (Robles')	   
insert into Town values ('San Alberto')	   
insert into Town values ('San Diego')	   
insert into Town values ('San Martín')	   
insert into Town values ('Tamalameque')	   
insert into Town values ('Montería')	   
insert into Town values ('Ayapel')	   
insert into Town values ('Buenavista')	   
insert into Town values ('Canalete')	   
insert into Town values ('Cereté')	   
insert into Town values ('Chima')	   
insert into Town values ('Chinú')	   
insert into Town values ('Ciénaga de Oro')	   
insert into Town values ('Cotorra')	   
insert into Town values ('La Apartada Frontera')   
insert into Town values ('Lorica')	   
insert into Town values ('Los Córdobas')	   
insert into Town values ('Momil')	   
insert into Town values ('Montelíbano')	   
insert into Town values ('Monitos')	   
insert into Town values ('Planeta Rica')	   
insert into Town values ('Pueblo Nuevo')	   
insert into Town values ('Puerto Escondido')	   
insert into Town values ('Puerto Libertador')	   
insert into Town values ('Purísima')	   
insert into Town values ('Sahagun')	   
insert into Town values ('San Andrés Sotavento')	   
insert into Town values ('San Antero')	   
insert into Town values ('San Bernardo del Viento')	   
insert into Town values ('San Carlos')	   
insert into Town values ('San Pelayo')	   
insert into Town values ('Tierralta')	   
insert into Town values ('Valencia')	   
insert into Town values ('Agua de Dios')	   
insert into Town values ('Albán')	   
insert into Town values ('Anapoima')	   
insert into Town values ('Anolaima')	   
insert into Town values ('Arbeláez')	   
insert into Town values ('Beltrán')	   
insert into Town values ('Bituima')	   
insert into Town values ('Bojacá')	   
insert into Town values ('Cabrera')	   
insert into Town values ('Cachipay')	   
insert into Town values ('Cajicá')	   
insert into Town values ('Caparrapí')	   
insert into Town values ('Cáqueza')	   
insert into Town values ('Carmen de Carupa')	   
insert into Town values ('Chaguaní')	   
insert into Town values ('Chía')	   
insert into Town values ('Chipaque')	   
insert into Town values ('Choachí')	   
insert into Town values ('Chocontá')	   
insert into Town values ('Cogua')	   
insert into Town values ('Cota')	   
insert into Town values ('Cucunubá')	   
insert into Town values ('El Colegio')	   
insert into Town values ('El Peñón')	   
insert into Town values ('El Rosal')	   
insert into Town values ('Facatativá')	   
insert into Town values ('Fómeque')	   
insert into Town values ('Fosca')	   
insert into Town values ('Funza')	   
insert into Town values ('Fúquene')	   
insert into Town values ('Fusagasugá')	   
insert into Town values ('Gachalá')	   
insert into Town values ('Gachancipá')	   
insert into Town values ('Gachetá')	   
insert into Town values ('Gama')	   
insert into Town values ('Girardot')	   
insert into Town values ('Granada')	   
insert into Town values ('Guachetá')	   
insert into Town values ('Guaduas')	   
insert into Town values ('Guasca')	   
insert into Town values ('Guataquí')	   
insert into Town values ('Guatavita')	   
insert into Town values ('Guayabal de Siquima')	   
insert into Town values ('Guayabetal')	   
insert into Town values ('Gutiérrez')	   
insert into Town values ('Jerusalén')	   
insert into Town values ('Junín')	   
insert into Town values ('La Calera')	   
insert into Town values ('La Mesa')	   
insert into Town values ('La Palma')	   
insert into Town values ('La Peña')	   
insert into Town values ('La Vega')	   
insert into Town values ('Lenguazaque')	   
insert into Town values ('Machetá')	   
insert into Town values ('Madrid')	   
insert into Town values ('Manta')	   
insert into Town values ('Medina')	   
insert into Town values ('Mosquera')	   
insert into Town values ('Nariño')	   
insert into Town values ('Nemocón')	   
insert into Town values ('Nilo')	   
insert into Town values ('Nimaima')	   
insert into Town values ('Nocaima')	   
insert into Town values ('Venecia (Ospina Pérez')   
insert into Town values ('Pacho')	   
insert into Town values ('Paime')	   
insert into Town values ('Pandi')	   
insert into Town values ('Paratebueno')	   
insert into Town values ('Pasca')	   
insert into Town values ('Puerto Salgar')	   
insert into Town values ('Pulí')	   
insert into Town values ('Quebradanegra')	   
insert into Town values ('Quetame')	   
insert into Town values ('Quipile')	   
insert into Town values ('Rafael')	   
insert into Town values ('Ricaurte')	   
insert into Town values ('San Antonio de Tequendama')	   
insert into Town values ('San Bernardo')	   
insert into Town values ('San Cayetano')	   
insert into Town values ('San Francisco')	   
insert into Town values ('San Juan de Rioseco')	   
insert into Town values ('Sasaima')	   
insert into Town values ('Sesquilé')	   
insert into Town values ('Sibate')	   
insert into Town values ('Silvania')	   
insert into Town values ('Simijaca')	   
insert into Town values ('Soacha')	   
insert into Town values ('Sopó')	   
insert into Town values ('Subachoque')	   
insert into Town values ('Suesca')	   
insert into Town values ('Supatá')	   
insert into Town values ('Susa')	   
insert into Town values ('Sutatausa')	   
insert into Town values ('Tabio')	   
insert into Town values ('Tausa')	   
insert into Town values ('Tena')	   
insert into Town values ('Tenjo')	   
insert into Town values ('Tibacuy')	   
insert into Town values ('Tibirita')	   
insert into Town values ('Tocaima')	   
insert into Town values ('Tocancipá')	   
insert into Town values ('Topaipí')	   
insert into Town values ('Ubalá')	   
insert into Town values ('Ubaque')	   
insert into Town values ('Ubaté')	   
insert into Town values ('Une')	   
insert into Town values ('Útica')	   
insert into Town values ('Vergara')	   
insert into Town values ('Viani')	   
insert into Town values ('Villagómez')	   
insert into Town values ('Villapinzón')	   
insert into Town values ('Villeta')	   
insert into Town values ('Viotá')	   
insert into Town values ('Yacopí')	   
insert into Town values ('Zipacón')	   
insert into Town values ('Zipaquirá')	   
insert into Town values ('Quibdó')	   
insert into Town values ('Acandí')	   
insert into Town values ('Alto Baudó (Pie de Pato')	   
insert into Town values ('Atrato Yuto')	   
insert into Town values ('Bagadó')	   
insert into Town values ('Bahía Solano (Mútis')	   
insert into Town values ('Bajo Baudó (Pizarro')	   
insert into Town values ('Bojayá (Bellavista')	   
insert into Town values ('Cantón de San Pablo')	   
insert into Town values ('Condoto')	   
insert into Town values ('El Carmen')	   
insert into Town values ('El Litoral de San Juan')	   
insert into Town values ('Itsmina')	   
insert into Town values ('Juradó')	   
insert into Town values ('Lloró')	   
insert into Town values ('Novita')	   
insert into Town values ('Nuquí')	   
insert into Town values ('Riosucio')	   
insert into Town values ('San José del Palmar')	   
insert into Town values ('Sipí')	   
insert into Town values ('Tadó')	   
insert into Town values ('Unguía')	   
insert into Town values ('Guainía 94 Inírida')	   
insert into Town values ('Guaviare 95 San José del Guaviare')	   
insert into Town values ('Calamar')	   
insert into Town values ('El Retorno')	   
insert into Town values ('Miraflores')	   
insert into Town values ('Neiva')	   
insert into Town values ('Acevedo')	   
insert into Town values ('Agrado')	   
insert into Town values ('Aipe')	   
insert into Town values ('Algeciras')	   
insert into Town values ('Altamira')	   
insert into Town values ('Baraya')	   
insert into Town values ('Campoalegre')	   
insert into Town values ('Colombia')	   
insert into Town values ('Elías')	   
insert into Town values ('Garzón')	   
insert into Town values ('Gigante')	   
insert into Town values ('Guadalupe')	   
insert into Town values ('Hobo')	   
insert into Town values ('Iquira')	   
insert into Town values ('Isnos')	   
insert into Town values ('La Argentina')	   
insert into Town values ('La Plata')	   
insert into Town values ('Nátaga')	   
insert into Town values ('Oporapa')	   
insert into Town values ('Paicol')	   
insert into Town values ('Palermo')	   
insert into Town values ('Palestina')	   
insert into Town values ('Pital')	   
insert into Town values ('Pitalito')	   
insert into Town values ('Rivera')	   
insert into Town values ('Saladoblanco')	   
insert into Town values ('San Agustín')	   
insert into Town values ('Santa María')	   
insert into Town values ('Suazá')	   
insert into Town values ('Tarqui')	   
insert into Town values ('Tesalia')	   
insert into Town values ('Tello')	   
insert into Town values ('Teruel')	   
insert into Town values ('Timaná')	   
insert into Town values ('Villavieja')	   
insert into Town values ('Yaguará')	   
insert into Town values ('Riohacha')	   
insert into Town values ('Barrancas')	   
insert into Town values ('Dibulla')	   
insert into Town values ('Distracción')	   
insert into Town values ('El Molino')	   
insert into Town values ('Fonseca')	   
insert into Town values ('Hatonuevo')	   
insert into Town values ('Maicao')	   
insert into Town values ('Manaure')	   
insert into Town values ('San Juan del Cesar')	   
insert into Town values ('Uribia')	   
insert into Town values ('Urumita')	   
insert into Town values ('Villanueva')	   
insert into Town values ('Santa Marta')	   
insert into Town values ('Aracataca')	   
insert into Town values ('Ariguaní (El Difícil')	   
insert into Town values ('Cerro San Antonio')	   
insert into Town values ('Chivolo')	   
insert into Town values ('Ciénaga')	   
insert into Town values ('El Banco')	   
insert into Town values ('El Piñón')	   
insert into Town values ('El Retén')	   
insert into Town values ('Fundación')	   
insert into Town values ('Guamal')	   
insert into Town values ('Pedraza')	   
insert into Town values ('Pijiño del Carmen')	   
insert into Town values ('Pivijay')	   
insert into Town values ('Plato')	   
insert into Town values ('Publoviejo')	   
insert into Town values ('Remolino')	   
insert into Town values ('Salamina')	   
insert into Town values ('San Sebastián de Buuenavista')	   
insert into Town values ('San Zenón')	   
insert into Town values ('Santa Ana')	   
insert into Town values ('Sitionuevo')	   
insert into Town values ('Tenerife')	   
insert into Town values ('Meta 50 Villavicencio')	   
insert into Town values ('Acacias')	   
insert into Town values ('Barranca de Upía')	   
insert into Town values ('Cabuyaro')	   
insert into Town values ('Castilla la Nueva')	   
insert into Town values ('Cubarral')	   
insert into Town values ('Cumaral')	   
insert into Town values ('El Calvario')	   
insert into Town values ('El Castillo')	   
insert into Town values ('El Dorado')	   
insert into Town values ('Fuente de Oro')	   
insert into Town values ('Granada')	   
insert into Town values ('Guamal')	   
insert into Town values ('Mapiripán')	   
insert into Town values ('Mesetas')	   
insert into Town values ('La Macarena')	   
insert into Town values ('La Uribe')	   
insert into Town values ('Lejanías')	   
insert into Town values ('Puerto Concordia')	   
insert into Town values ('Puerto Gaitán')	   
insert into Town values ('Puerto López')	   
insert into Town values ('Puerto Lleras')	   
insert into Town values ('Puerto Rico')	   
insert into Town values ('Restrepo')	   
insert into Town values ('San Carlos de Guaroa')	   
insert into Town values ('San Juan de Arama')	   
insert into Town values ('San Juanito')	   
insert into Town values ('San Martín')	   
insert into Town values ('Vistahermosa')	   
insert into Town values ('Pasto')	   
insert into Town values ('Albán (San José')	   
insert into Town values ('Aldana')	   
insert into Town values ('Ancuyá')	   
insert into Town values ('Arboleda (Berruecos')	   
insert into Town values ('Barbacoas')	   
insert into Town values ('Belén')	   
insert into Town values ('Buesaco')	   
insert into Town values ('Colón (Génova')   
insert into Town values ('Consacá')	   
insert into Town values ('Contadero')	   
insert into Town values ('Córdoba')	   
insert into Town values ('Cuaspud (Carlosama')	   
insert into Town values ('Cumbal')	   
insert into Town values ('Cumbitará')	   
insert into Town values ('Chachagüi')	   
insert into Town values ('El Charco')	   
insert into Town values ('El Rosario')	   
insert into Town values ('El Tablón')	   
insert into Town values ('El Tambo')	   
insert into Town values ('Funes')	   
insert into Town values ('Guachucal')	   
insert into Town values ('Guaitarilla')	   
insert into Town values ('Gualmatán')	   
insert into Town values ('Iles')	   
insert into Town values ('Imúes')	   
insert into Town values ('Ipiales')	   
insert into Town values ('La Cruz')	   
insert into Town values ('La Florida')	   
insert into Town values ('La Llanada')	   
insert into Town values ('La Tola')	   
insert into Town values ('La Unión')	   
insert into Town values ('Leiva')	   
insert into Town values ('Linares')	   
insert into Town values ('Los Andes (Sotomayor')	   
insert into Town values ('Magüí (Payán')
insert into Town values ('Mallama (Piedrancha')	   
insert into Town values ('Mosquera')	   
insert into Town values ('Olaya')	   
insert into Town values ('Ospina')	   
insert into Town values ('Francisco Pizarro')	   
insert into Town values ('Policarpa')	   
insert into Town values ('Potosí')	   
insert into Town values ('Providencia')	   
insert into Town values ('Puerres')	   
insert into Town values ('Pupiales')	   
insert into Town values ('Ricaurte')	   
insert into Town values ('Roberto Payán (San José')	   
insert into Town values ('Samaniego')	   
insert into Town values ('Sandoná')	   
insert into Town values ('San Bernardo')	   
insert into Town values ('San Lorenzo')	   
insert into Town values ('San Pablo')	   
insert into Town values ('San Pedro de Cartago')	   
insert into Town values ('Santa Bárbara (Iscuandé')	   
insert into Town values ('Santa Cruz (Guachávez')	   
insert into Town values ('Sapuyés')	   
insert into Town values ('Taminango')	   
insert into Town values ('Tangua')	   
insert into Town values ('Tumaco')	   
insert into Town values ('Túquerres')	   
insert into Town values ('Yacuanquer')	   
insert into Town values ('Cúcuta')	   
insert into Town values ('Abrego')	   
insert into Town values ('Arboledas')	   
insert into Town values ('Bochalema')	   
insert into Town values ('Bucarasica')	   
insert into Town values ('Cácota')	   
insert into Town values ('Cáchira')	   
insert into Town values ('Chinácota')	   
insert into Town values ('Chitagá')	   
insert into Town values ('Convención')	   
insert into Town values ('Cucutilla')	   
insert into Town values ('Durania')	   
insert into Town values ('El Carmen')	   
insert into Town values ('El Tarra')	   
insert into Town values ('El Zulia')	   
insert into Town values ('Gramalote')	   
insert into Town values ('Hacarí')	   
insert into Town values ('Herrán')	   
insert into Town values ('Labateca')	   
insert into Town values ('La Esperanza')	   
insert into Town values ('La Playa')	   
insert into Town values ('Los Patios')	   
insert into Town values ('Lourdes')	   
insert into Town values ('Mutiscua')	   
insert into Town values ('Ocaña')	   
insert into Town values ('Pamplona')	   
insert into Town values ('Pamplonita')	   
insert into Town values ('Puerto Santander')	   
insert into Town values ('Ragonvalia')	   
insert into Town values ('Salazar')	   
insert into Town values ('San Calixto')	   
insert into Town values ('San Cayetano')	   
insert into Town values ('Santiago')	   
insert into Town values ('Sardinata')	   
insert into Town values ('Silos')	   
insert into Town values ('Teorama')	   
insert into Town values ('Tibú')	   
insert into Town values ('Toledo')	   
insert into Town values ('Villacaro')	   
insert into Town values ('Villa del Rosario')	   
insert into Town values ('Mocoa')	   
insert into Town values ('Colón')	   
insert into Town values ('Orito')	   
insert into Town values ('Puerto Asís')	   
insert into Town values ('Puerto Caicedo')	   
insert into Town values ('Puerto Guzmán')	   
insert into Town values ('Puerto Leguízamo')	   
insert into Town values ('Sibundoy')	   
insert into Town values ('San Francisco')	   
insert into Town values ('San Miguel')	   
insert into Town values ('Santiago')	   
insert into Town values ('Villa Gamuez La Hormiga')	   
insert into Town values ('Villa Garzón')	   
insert into Town values ('Quindío 63 Armenia')	   
insert into Town values ('Buenavista')	   
insert into Town values ('Calarcá')	   
insert into Town values ('Circasia')	   
insert into Town values ('Córdoba')	   
insert into Town values ('Filandia')	   
insert into Town values ('Génova')	   
insert into Town values ('La Tebaida')	   
insert into Town values ('Montenegro')	   
insert into Town values ('Pijao')	   
insert into Town values ('Quimbaya')	   
insert into Town values ('Salento')	   
insert into Town values ('Pereira')	   
insert into Town values ('Apía')	   
insert into Town values ('Balboa')	   
insert into Town values ('Belén de Umbría')	   
insert into Town values ('Dos Quebradas')	   
insert into Town values ('Guatica')	   
insert into Town values ('La Celia')	   
insert into Town values ('La Virginia')	   
insert into Town values ('Marsella')	   
insert into Town values ('Mistrato')	   
insert into Town values ('Pueblo Rico')	   
insert into Town values ('Quinchia')	   
insert into Town values ('Santa Rosa de Cabal')	   
insert into Town values ('Santuario')	   
insert into Town values ('San Andrés')	   
insert into Town values ('Providencia')	   
insert into Town values ('Bucaramanga')	   
insert into Town values ('Aguada')	   
insert into Town values ('Albania')	   
insert into Town values ('Aratoca')	   
insert into Town values ('Barbosa')	   
insert into Town values ('Barichara')	   
insert into Town values ('Barrancabermeja')	   
insert into Town values ('Betulia')	   
insert into Town values ('Bolívar')	   
insert into Town values ('Cabrera')	   
insert into Town values ('California')	   
insert into Town values ('Capitanejo')	   
insert into Town values ('Carcasí')	   
insert into Town values ('Cepitá')	   
insert into Town values ('Cerrito')	   
insert into Town values ('Charalá')	   
insert into Town values ('Charta')	   
insert into Town values ('Chima')	   
insert into Town values ('Chipatá')	   
insert into Town values ('Cimitarra')	   
insert into Town values ('Concepción')	   
insert into Town values ('Confines')	   
insert into Town values ('Contratación')	   
insert into Town values ('Coromoro')	   
insert into Town values ('Curití')	   
insert into Town values ('El Carmen')	   
insert into Town values ('El Guacamayo')	   
insert into Town values ('El Peñón')	   
insert into Town values ('El Playón')	   
insert into Town values ('Encino')	   
insert into Town values ('Enciso')	   
insert into Town values ('Florián')	   
insert into Town values ('Floridablanca')	   
insert into Town values ('Galán')	   
insert into Town values ('Gámbita')	   
insert into Town values ('Girón')	   
insert into Town values ('Guaca')	   
insert into Town values ('Guadalupe')	   
insert into Town values ('Guapotá')	   
insert into Town values ('Guavata')	   
insert into Town values ('Guepsa')	   
insert into Town values ('Hato')	   
insert into Town values ('Jesús María')	   
insert into Town values ('Jordán')	   
insert into Town values ('La Belleza')	   
insert into Town values ('Landázuri')	   
insert into Town values ('La Paz')	   
insert into Town values ('Lebrija')	   
insert into Town values ('Los Santos')	   
insert into Town values ('Macaravita')	   
insert into Town values ('Málaga')	   
insert into Town values ('Matanza')	   
insert into Town values ('Mogotes')	   
insert into Town values ('Molagavita')	   
insert into Town values ('Ocamonte')	   
insert into Town values ('Oiba')	   
insert into Town values ('Onzága')	   
insert into Town values ('Palmar')	   
insert into Town values ('Palmas del Socorro')	   
insert into Town values ('Páramo')	   
insert into Town values ('Pie de Cuesta')	   
insert into Town values ('Pinchote')	   
insert into Town values ('Puente Nacional')	   
insert into Town values ('Puerto Parra')	   
insert into Town values ('Puerto Wilches')	   
insert into Town values ('Rionegro')	   
insert into Town values ('Sabana de Torres')	   
insert into Town values ('San Andrés')	   
insert into Town values ('San Benito')	   
insert into Town values ('San Gil')	   
insert into Town values ('San Joaquín')	   
insert into Town values ('San José de Miranda')	   
insert into Town values ('San Miguel')	   
insert into Town values ('San Vicente de Chucurí')	   
insert into Town values ('Santa Bárbara')	   
insert into Town values ('Santa Helena del Opón')	   
insert into Town values ('Simacota')	   
insert into Town values ('Socorro')	   
insert into Town values ('Suaita')	   
insert into Town values ('Sucre')	   
insert into Town values ('Suratá')	   
insert into Town values ('Tona')	   
insert into Town values ('Valle de San José')	   
insert into Town values ('Vélez')	   
insert into Town values ('Vetas')	   
insert into Town values ('Villanueva')	   
insert into Town values ('Zapatoca')	   
insert into Town values ('Sincelejo')	   
insert into Town values ('Buenavista')	   
insert into Town values ('Caimito')	   
insert into Town values ('Coloso Ricaurte')	   
insert into Town values ('Corozal')	   
insert into Town values ('Chalán')	   
insert into Town values ('Galeras (Nueva Granada')	   
insert into Town values ('Guarandá')	   
insert into Town values ('La Unión')	   
insert into Town values ('Los Palmitos')	   
insert into Town values ('Majagual')	   
insert into Town values ('Morroa')	   
insert into Town values ('Ovejas')	   
insert into Town values ('Palmito')	   
insert into Town values ('Sampués')	   
insert into Town values ('San Benito Abad')	   
insert into Town values ('San Juan de Betulia')	   
insert into Town values ('San Marcos')	   
insert into Town values ('San Onofre')	   
insert into Town values ('San Pedro')	   
insert into Town values ('Sincé')	   
insert into Town values ('Sucre')	   
insert into Town values ('Tolú')	   
insert into Town values ('Toluviejo')	   
insert into Town values ('Ibagué')	   
insert into Town values ('Alpujarra')	   
insert into Town values ('Alvarado')	   
insert into Town values ('Ambalema')	   
insert into Town values ('Anzoátegui')	   
insert into Town values ('Armero (Guayabal')   
insert into Town values ('Ataco')	   
insert into Town values ('Cajamarca')	   
insert into Town values ('Carmen de Apicalá')	   
insert into Town values ('Casabianca')	   
insert into Town values ('Chaparral')	   
insert into Town values ('Coello')	   
insert into Town values ('Coyaima')	   
insert into Town values ('Cunday')	   
insert into Town values ('Dolores')	   
insert into Town values ('Espinal')	   
insert into Town values ('Falán')	   
insert into Town values ('Flandes')	   
insert into Town values ('Fresno')	   
insert into Town values ('Guamo')	   
insert into Town values ('Herveo')	   
insert into Town values ('Honda')	   
insert into Town values ('Icononzo')	   
insert into Town values ('Lérida')	   
insert into Town values ('Líbano')	   
insert into Town values ('Mariquita')	   
insert into Town values ('Melgar')	   
insert into Town values ('Murillo')	   
insert into Town values ('Natagaima')	   
insert into Town values ('Ortega')	   
insert into Town values ('Palocabildo')	   
insert into Town values ('Piedras')	   
insert into Town values ('Planadas')	   
insert into Town values ('Prado')	   
insert into Town values ('Purificación')	   
insert into Town values ('Rioblanco')	   
insert into Town values ('Roncesvalles')	   
insert into Town values ('Rovira')	   
insert into Town values ('Saldaña')	   
insert into Town values ('San Antonio')	   
insert into Town values ('San Luis')	   
insert into Town values ('Santa Isabel')	   
insert into Town values ('Suárez')	   
insert into Town values ('Valle de San Juan')	   
insert into Town values ('Venadillo')	   
insert into Town values ('Villahermosa')	   
insert into Town values ('Villarrica')	   
insert into Town values ('Cali')	   
insert into Town values ('Alcalá')	   
insert into Town values ('Andalucía')	   
insert into Town values ('Ansermanuevo')	   
insert into Town values ('Argelia')	   
insert into Town values ('Bolívar')	   
insert into Town values ('Buenaventura')	   
insert into Town values ('Buga')	   
insert into Town values ('Bugalagrande')	   
insert into Town values ('Caicedonia')	   
insert into Town values ('Calima (Darién')	   
insert into Town values ('Candelaria')	   
insert into Town values ('Cartago')	   
insert into Town values ('Dagua')	   
insert into Town values ('El Águila')	   
insert into Town values ('El Cairo')	   
insert into Town values ('El Cerrito')	   
insert into Town values ('El Dovio')	   
insert into Town values ('Florida')	   
insert into Town values ('Ginebra')	   
insert into Town values ('Guacarí')	   
insert into Town values ('Jamundí')	   
insert into Town values ('La Cumbre')	   
insert into Town values ('La Unión')	   
insert into Town values ('La Victoria')	   
insert into Town values ('Obando')	   
insert into Town values ('Palmira')	   
insert into Town values ('Pradera')	   
insert into Town values ('Restrepo')	   
insert into Town values ('Riofrío')	   
insert into Town values ('Roldanillo')	   
insert into Town values ('San Pedro')	   
insert into Town values ('Sevilla')	   
insert into Town values ('Toro')	   
insert into Town values ('Trujillo')	   
insert into Town values ('Tuluá')	   
insert into Town values ('Ulloa')	   
insert into Town values ('Versalles')	   
insert into Town values ('Vijes')	   
insert into Town values ('Yotoco')	   
insert into Town values ('Yumbo')	   
insert into Town values ('Zarzal')	   
insert into Town values ('Vaupés 97 Mitú')	   
insert into Town values ('Carurú')	   
insert into Town values ('Tatamá')	   
insert into Town values ('Vichada 99 Puerto Carreño')	   
insert into Town values ('La Primavera')	   
insert into Town values ('Santa Rosalia')	   
insert into Town values ('Cumaribo')	 
go